### ISSUE TITLE
Achievement pop-up not shown when Frozen Cookies is loaded

### ISSUE THREAD

**Issue by tkn** [Icehawk78/FrozenCookies#111]
When using Frozen Cookies, the pop-ups for achievements are not shown. Other pop-ups such as when clicking a cookie or exploding a wrinkler seem to show correctly. Possibly related: 

When loading Frozen Cookies, I get several achievement pop-ups for one or multiple achievements that I have not earned, and are not registered as earned afterwards (not even after a reload). See screenshot.

![screen shot 2014-06-11 at 14 52 26](https://cloud.githubusercontent.com/assets/241624/3244393/69062d84-f167-11e3-8152-4526ce8c08f5.png)

**Comment by Icehawk78** [comment]
The underlying achievement display bug should be fixed now.

@pjie2 - your issue is related to the Easter season, and you didn't need to buy the Chocolate egg, just needed to buy the Easter season again to unlock the achievement. Unfortunately, there's not really a way to tell FC to slow down just to earn the achievement.
