### ISSUE TITLE
HC tracking is broken

### ISSUE THREAD

**Issue by Ariamaki** [Icehawk78/FrozenCookies#157]
FC currently think it has been over 80 days since my last HC and that I earn them at a rate of -11,720 per hour, despite it just ticking over a new HC as I wrote this sentence. Same save from the Golden Switch issue should repro.

**Comment by Icehawk78** [comment]
That's actually likely only a bug if you last ran FC on live before the update and haven't reset since then, due to the change in HC calculations. When you reset it should fix itself, or you can run this in your console:

FrozenCookies.lastHCAmount = Game.prestige;

That should kick it back into tracking.

If these don't work, please re-open the bug and I'll look into it more.
