### ISSUE TITLE
Production Multiplier Estimation

### ISSUE THREAD

**Issue by Ariamaki** [Icehawk78/FrozenCookies#160]
Currently, it seems that FC doesn't recognize the updated value for a lot of items (all cookies, arcane sugar, etc) are multiplicative (specific example, Arcane Sugar is literally +5% production as a final unique multiplier), so it doesn't purchase them even when it's definitely the highest actual efficiency, or even when their cost is less than 1 second of CpS.

**Comment by Icehawk78** [comment]
FC knows exactly how much each upgrade is worth, because it uses the game's own calculations to determine that. Check the internal information section to review the math if you want, but it's highly unlikely that the things you're seeing are actually the most efficient, unless you're internally using a different formula.

If you have specific examples of it calculating wrong, I can review it, but it's almost certainly not doing so.

**Comment by Ariamaki** [comment]
In a situation where I already had 193 Prisms and the current efficiency-based build-chain was towards Prism for Lux Sanctorum, the game assumed ignoring Arcane Sugar was the correct purchase, despite its price (117 trillion) being a tiny fraction of my CpS (a bit over 58 sextillion) and my post-purchase CpS (~61 sextillion) being far higher than the difference of the next single Prism.

**Comment by Icehawk78** [comment]
That's correct. The efficiency calculation takes into account both the cost of the item and the difference in CPS it will give.

With the chained upgrades, FC actually treats all prerequisite buildings and upgrades are simply part of the cost of the final upgrade, so if it was saving up for Lux Sanctorum, FC calculated that the efficiency (ie cost/current cps + cost/delta cps) for (7 prisms + Lux Sanctorum) was better than for Arcane Sugar.

While counterintuitive, this is correct, and is the basis for the entire FC project.
