### ISSUE TITLE
Auto Purchase no longer working in V2

### ISSUE THREAD

**Issue by ama4tf** [Icehawk78/FrozenCookies#162]
Despite turning auto-click on, it looks like it doesn't actually automatically click. Also it gives bad estimates (like 9 hours when it actually takes like 30 minutes)

**Comment by BaesFr** [comment]
I had a bug similar to this one. The chrome debug Panel was open but when
I  close it everything's seems to return  to normal.

I dont' know why

**Comment by Icehawk78** [comment]
Have you verified whether or not it is saving up for the Golden Cookie bank?

And to verify whether or not it's clicking for you, you can go to the stats screen and see if the "Cookie clicks" number is increasing.

Can you verify both of these things? I ask because I have not seen either of these issues on my end.

**Comment by ama4tf** [comment]
It was saving up for the bank
