### ISSUE TITLE
possible bug with autobuy and season switching

### ISSUE THREAD

**Issue by rapunsell** [Icehawk78/FrozenCookies#169]
So I use autobuy a fair amount but I mix in my own preferences/quirks with respect to some purchases and upgrades. On most runs, I prefer to try to get the upgrades (cookies, eggs, etc.) from Halloween, Easter and Valentine's Day before Frozen Cookies thinks they're optimal. I did that this run and the last run (both on Cookie Clicker V. 2) and ran into the same bug both times. 

When I buy these other holiday biscuits and purchase the cookies/eggs, the upgrades themselves disappear from the "to buy" list as I get them, but the purchase of the seasonal biscuits does not. So later on, if I keep autobuy on, Frozen Cookie switches me back to Halloween because it believes I still need the Halloween cookies. I left it running overnight in the hopes that it would figure out that I did in fact already have all seven Halloween cookies, but apparently it's not going to figure it out. I guess it's waiting from some kind of trigger that's never going to happen since I already have all the cookies. (The Easter and Valentines Day biscuits also continue to appear on the "to buy" list, so I imagine that I'd have the same problem with those holidays later on if I could ever get Frozen Cookies to believe that I was really done with Halloween.)

For now I'm turning off autobuy and switching back to Christmas, but I thought you'd want to know about this bug. 

P.S. Thanks for this script. I love it!

**Comment by Icehawk78** [comment]
Have you bought the Halloween heavenly upgrade, but not Business Day?

Because the season-related upgrades other than Valentines and Christmas provide a boost to Golden Cookie spawn rates, which make those seasons significantly more effective than the Reindeer for Christmas, which is why it will try to switch away. Business Day is far and away the most effective, because it's a 5% boost rather than a 2% boost, but both of those are more effective than Reindeer assuming you have your autoclicker set to a high enough rate.

**Comment by rapunsell** [comment]
Ah! I have indeed bought the Halloween upgrade but not yet Business Day. I didn't realize the other holidays were more effective now, and I guess after this run I'll be buying the Business day upgrade. Thanks for the explanation and I'm glad it's not a bug!

**Comment by Icehawk78** [comment]
Glad I could help!
