### ISSUE TITLE
Change to Valentine's Day immediately after Santa's Dominion?

### ISSUE THREAD

**Issue by StaplerGuy** [Icehawk78/FrozenCookies#170]
Is there some point in the millions of prestige where switching and buying the Valentine's cookies immediately after Santa's Dominion (then to Easter, then back to Christmas) rather than waiting until all the Christmas cookies have dropped is worth the single additional season switch lifetime? It seems to me like it's only worse if you're going for a _long_ run, such that the chocolate lost from the cost of additional season switch is larger than (gain from V. cookies + chocolate gain of same + chocolate gain from additional things bought from those cookies)... but I don't think the content currently exists to justify that.

Also, would you have preferred I post this somewhere other than your github?

**Comment by StaplerGuy** [comment]
Heck, now that I think about it, if you _really_ want to maximize time in Business Day, shouldn't FC also autobuy Omelette eventually? Faster egg drops means more time for business business business.

**Comment by Icehawk78** [comment]
Unfortunately, the lack of changing that currently exists is done because otherwise it would constantly buy all of the seasons trying to get to the unlockable ones. It's not an ideal scenario, but with the architecture that FC has for its recommendations, without adding a bunch of special rules, it's the best it'll get.
